# preliminaries

## data manipulation

In [ ]:
import torch
x=torch.arange(12)
print(x)
print(x.shape)
print(x.numel())
x=x.reshape(3,4)
print(x)

print(torch.zeros((2,3,4)))

print(torch.ones((2,2,2)))
#正态分布
print(torch.randn(3,4))
print(torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]))
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y,torch.exp(x)

X=torch.arange(15,dtype=torch.int32).reshape((5,3))
print("X=",X)
Y=torch.tensor([[2,1,4],[1,2,3],[4,3,2],[3,4,5]])
print("Y=",Y)
torch.cat((X,Y),dim=0)
Y=torch.cat((Y,torch.tensor([[6,5,7]])),dim=0)
print(torch.cat((X,Y),dim=1))
#dim=0 按行拼接，dim=1 按列拼接
print(X==Y)
# print((X<Y)and(X>Y)) 非逻辑与
print((X<Y)&(X>Y))
print((X<Y)|(X>Y))
print(X.sum())
print(X.sum(dim=0),X.sum(dim=1))
print((X+Y).sum())  
#广播机制
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
print(a+b)
#索引和切片
X[-1],X[1:3]
X[1,2]=9
print(X)
X[0:2,1:3]=12
print(X)
X[0:2,1:3]=torch.tensor([10,11])
print(X)
X[0:2,:]=12
print(X)
#内存节省 使用原地址更新数值
before=id(Y)
Y=Y+X
#Y=Y+X 会开辟新的内存
print("id(Y)=",id(Y))
print("before=",before)
#采用切片的分配方法节省内存 避免开辟新的内存
before=id(Y)
Y+=X
Y[:]=X+Y
print("id(Y)=",id(Y))
print("before=",before)

#转换Python对象
A = X.numpy()
B = torch.tensor(A)
# print("A=",A,"B=",B)
print("type(A)=",type(A), "type(B)=",type(B))

#转换为标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor([[-0.6717, -0.1489,  0.8860, -0.1938],
        [-0.3539, -1.6176,  0.8188,  0.0190],
        [ 0.9926, -0.0781, -0.3632,  1.1429]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
X= tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)
Y= tensor([[2, 1, 4],
        [1, 2, 3],
        [4, 3, 2],
        [3, 4, 5]])
tensor([[ 0,  1,  2,  2,  1,  4],
        [ 3,  4,  5,  1,  2,  3],
        [ 6,  7,  8,  4,  3,  2],
        [ 9, 10, 11,  3,  4,  5],
        [12, 13, 14,  6,  5,  7]])
tensor([

(tensor([3.5000]), 3.5, 3.5, 3)

广播规则：
从右往左比，每一维必须满足：
相等，或其中一个是 1

In [ ]:
import torch

x=torch.arange(120,dtype=torch.float32).reshape((3,4,5,2,1))
# print(x,"\n",y)
y=torch.ones((3,1,5,1,5))
# print(x+1)
print(x+y)


## data preprocessing

In [ ]:
#数据预处理
import os
#数据集读取
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')
import pandas as pd
data=pd.read_csv(data_file)
print(data)
#缺失值处理
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
# NumRooms 为数值列可用均值；Alley 为字符串列，mean() 会报错，需 numeric_only 或分列处理
inputs = inputs.fillna(inputs.mean(numeric_only=True))
# inputs = inputs.fillna({"Alley": inputs["Alley"].mode()[0]})
print(inputs)
#onehot编码
inputs=pd.get_dummies(inputs,dummy_na=True,dtype=int)
# 单列（按序号）
# col = inputs.columns[1:]
# inputs[col] = inputs[col].astype(int)
print(inputs)
#transfer to tensor
print(X,Y)
X,Y=torch.tensor(inputs.values.astype(float)),torch.tensor(outputs.values.astype(float))
# X,Y=X.to(torch.float32),Y.to(torch.float32)
# X,Y=torch.tensor(inputs.to_numpy(dtype=float)),torch.tensor(outputs.to_numpy(dtype=float))


   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1
tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64) tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)


In [ ]:
# 数据预处理：更多行和列 + 删除缺失值最多的列 + 转张量
import os
import pandas as pd
import torch

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')

# 创建包含更多行和列的原始数据集
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,LotArea,YearBuilt,Condition,Price\n')
    f.write('NA,Pave,8450,2003,Normal,208500\n')
    f.write('2,NA,9600,1976,Normal,181500\n')
    f.write('4,NA,11250,2001,Abnorml,223500\n')
    f.write('3,NA,9550,1915,Normal,140000\n')
    f.write('NA,NA,14260,2000,Normal,250000\n')
    f.write('3,Grvl,14115,1993,Abnorml,143000\n')
    f.write('2,NA,10084,2004,Normal,307000\n')

# 读取原始数据
raw_data = pd.read_csv(data_file)
print('原始数据集:')
print(raw_data)

# 按列序号划分特征和标签（最后一列是 Price）
inputs = raw_data.iloc[:, :-1].copy()
outputs = raw_data.iloc[:, -1].copy()

# 删除缺失值最多的列
missing_counts = inputs.isna().sum()
missing_counts_row=inputs.isna().sum(axis=1)
print(missing_counts)
print(missing_counts_row)
most_missing_col = missing_counts.idxmax()
most_missing_row=missing_counts_row.idxmax()
inputs = inputs.drop(columns=[most_missing_col])
print(f'\n删除缺失值最多的列: {most_missing_col}')
print(f'\n删除缺失值最多的行: {most_missing_row}')

# 数值列用均值填充，类别列用众数填充
num_cols = inputs.select_dtypes(include='number').columns
cat_cols = inputs.select_dtypes(exclude='number').columns

inputs[num_cols] = inputs[num_cols].fillna(inputs[num_cols].mean())
for c in cat_cols:
    inputs[c] = inputs[c].fillna(inputs[c].mode()[0])

# one-hot 编码
inputs = pd.get_dummies(inputs, dummy_na=False, dtype=int)
print('\n预处理后特征:')
print(inputs)

# 转换为张量格式
tensor_X = torch.tensor(inputs.to_numpy(dtype=float), dtype=torch.float32)
tensor_y = torch.tensor(outputs.to_numpy(dtype=float), dtype=torch.float32)

原始数据集:
   NumRooms Alley  LotArea  YearBuilt Condition   Price
0       NaN  Pave     8450       2003    Normal  208500
1       2.0   NaN     9600       1976    Normal  181500
2       4.0   NaN    11250       2001   Abnorml  223500
3       3.0   NaN     9550       1915    Normal  140000
4       NaN   NaN    14260       2000    Normal  250000
5       3.0  Grvl    14115       1993   Abnorml  143000
6       2.0   NaN    10084       2004    Normal  307000
NumRooms     2
Alley        5
LotArea      0
YearBuilt    0
Condition    0
dtype: int64
0    1
1    1
2    1
3    1
4    2
5    0
6    1
dtype: int64

删除缺失值最多的列: Alley

删除缺失值最多的行: 4

预处理后特征:
   NumRooms  LotArea  YearBuilt  Condition_Abnorml  Condition_Normal
0       2.8     8450       2003                  0                 1
1       2.0     9600       1976                  0                 1
2       4.0    11250       2001                  1                 0
3       3.0     9550       1915                  0                 1
4       2

pandas中：

axis=1指对列元素操作  sum()取行上列元素加和 dropna()判断某列有无Na 对整列删除

df.dropna(axis=1, how='all')   # 只删“全是NaN”的列

df.dropna(axis=1, thresh=2)    # 每列至少保留2个非NaN才不删

df.dropna(axis=1, subset=[...])# 对指定行子集检查列是否缺失

## linear algebra


In [7]:
import torch 
#标量 scalar
scalar=torch.tensor(1.0)
x=torch.arange(4)
x[3]
len(x)
x=torch.arange(60).reshape(3,4,5)
x.shape


torch.Size([3, 4, 5])

长度 单个数组元素个数

维度 向量长度  基本单位上元素个数

向量或轴的维度被用来表示向量或轴的长度，即向量或轴的元素数量。 然而，张量的维度用来表示张量具有的轴数。 在这个意义上，张量的某个轴的维数就是这个轴的长度。


In [ ]:
from numpy import dtype
import torch
from torch._refs import to 
#矩阵 matrix
x=torch.arange(36).reshape(6,6)
rows,cols=x.shape

T=torch.empty(rows,cols,dtype=x.dtype) #T=torch.empty((rows,cols),dtype=x.dtype)

for i in range(rows):
    for j in range(cols):
        T[j,i]=x[i,j]

'''
A = [[1,2,3],[4,5,6]]
rows, cols = len(A), len(A[0])
T = [[0]*rows for _ in range(cols)]

for i in range(rows):
    for j in range(cols):
        T[j][i] = A[i][j]
'''                

for k in range(rows*cols):
    i,j = divmod(k,cols)
    T[j,i]=x[i,j]

'''
q, r = divmod(a, b)
# 等价于
q = a // b
r = a % b
'''

print(x)
print(x.T)
print(T)
X1=x.T+x
X2=x@x.T
x_single=x*x.T
print(X1)
print(X2)
print(x_single)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])
tensor([[ 0,  6, 12, 18, 24, 30],
        [ 1,  7, 13, 19, 25, 31],
        [ 2,  8, 14, 20, 26, 32],
        [ 3,  9, 15, 21, 27, 33],
        [ 4, 10, 16, 22, 28, 34],
        [ 5, 11, 17, 23, 29, 35]])
tensor([[ 0,  6, 12, 18, 24, 30],
        [ 1,  7, 13, 19, 25, 31],
        [ 2,  8, 14, 20, 26, 32],
        [ 3,  9, 15, 21, 27, 33],
        [ 4, 10, 16, 22, 28, 34],
        [ 5, 11, 17, 23, 29, 35]])
tensor([[ 0,  7, 14, 21, 28, 35],
        [ 7, 14, 21, 28, 35, 42],
        [14, 21, 28, 35, 42, 49],
        [21, 28, 35, 42, 49, 56],
        [28, 35, 42, 49, 56, 63],
        [35, 42, 49, 56, 63, 70]])
tensor([[  55,  145,  235,  325,  415,  505],
        [ 145,  451,  757, 1063, 1369, 1675],
        [ 235,  757, 1279, 1801, 2323, 2845],
        [ 325, 1063, 1801, 2539, 3277, 401